spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: fidane
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: Fidane
      password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 7775
jwt:
  secret: 6vK0F7fZY4PbAlBPlZIVajxyIMkRjRjfbOZGLhFhZ+U=
  expiration: 86400000